[build]
command = "npx @cloudflare/next-on-pages@1"
pages_build_output_dir = ".vercel/output/static"

[build.environment]
NODE_VERSION = "20"

[site]
bucket = ".vercel/output/static"

[env.production]
name = "production" 