[build]
command = "npx @cloudflare/next-on-pages@1"
output_directory = ".vercel/output/static"

[build.environment]
NODE_VERSION = "20"

[site]
bucket = ".vercel/output/static"

[env.production]
name = "production" 